### ISSUE TITLE
dataset inaccessible

### ISSUE THREAD

**Issue by gukai330** [darthgera123/PanoHDR-NeRF#3]
Hi Mr. Pulkit Gera,

Thank you for your interesting work! I am Kai and also doing some research about 360 NeRF. 
I found you provide the link to the dataset but it is not accessible. 

do you consider releasing the dataset? which will be very useful to my research.

thank you in advance!

**Comment by MrKarimiD** [comment]
Hi!

I am one of the authors of this paper and I currently have access to the data. Can you please send me an email about this issue? mokad6(at-sign)ulaval.ca

Best,
Mohammad Reza Karimi Dastjerdi

**Comment by gukai330** [comment]
> 

Thank you for your reply, I have sent you an email regarding the dataset with my institute email.
